// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPTSobj.InfrastructureServices.Gateways.Database;

namespace RPTSobj.WebService.Migrations
{
    [DbContext(typeof(RPTSobjContext))]
    [Migration("20200601192203_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("RPTSobj.DomainObjects.rptsobj", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetroLine")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetroStation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebSite")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RPTSobjs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Ленинградский проспект, дом 36, строение 21 ",
                            MetroLine = "Долгушев Анатолий Петрович",
                            Name = "УЧРЕЖДЕНИЕ «МОСКОВСКИЙ ФИЗКУЛЬТУРНО-СПОРТИВНЫЙ КЛУБ «ЮНЫЙ ДИНАМОВЕЦ»",
                            WebSite = "63809221"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Краснобогатырская улица, дом 44, корпус 1",
                            MetroLine = "Чаплеевский Роман Павлович",
                            Name = "РЕГИОНАЛЬНАЯ ОБЩЕСТВЕННАЯ ОРГАНИЗАЦИЯ «ФЕДЕРАЦИЯ СКЕЙТБОРДИНГА»",
                            WebSite = "63809222"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Фурманный переулок, дом 10, строение 1",
                            MetroLine = "Папсуев Матвей Александрович",
                            Name = "Автономная некоммерческая организация «Ассоциация «Здоровая нация»",
                            WebSite = "63809223"
                        },
                        new
                        {
                            Id = 4L,
                            Address = "Новинский бульвар, дом 18, корпус 1",
                            MetroLine = "Сиваков Олег Петрович",
                            Name = "АВТОНОМНАЯ НЕКОММЕРЧЕСКАЯ ОРГАНИЗАЦИЯ ПО ПРОВЕДЕНИЮ СПОРТИВНЫХ И МАССОВЫХ МЕРОПРИЯТИЙ «ВЫДВИЖЕНИЕ»",
                            WebSite = "63809224 "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
